name: build-and-test

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e . pytest pyinstaller
      - name: Run tests
        env:
          PYTHONPATH: src
        run: python -m pytest -q
      - name: Build GUI executable
        run: |
          pyinstaller -n smdresistor-gui --onefile -w -F src/smdresistor/gui.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: smdresistor-gui-${{ matrix.os }}
          path: dist/*

